### ISSUE TITLE
Broken link in Actions & Action Handlers chapter

### ISSUE THREAD

**Issue by srcnuzn** [eclipse-glsp/glsp-website-source#94]
The link in [documentation/actionhandler/content.md#L30](https://github.com/eclipse-glsp/glsp-website-source/blob/master/content/documentation/actionhandler/content.md?plain=1#L30) from documentation chapter [Actions & Action Handlers](https://eclipse.dev/glsp/documentation/actionhandler/) points to https://eclipse.dev/documentation/protocol/ which returns 404 for me. 

The correct link contains glsp in the url: https://www.eclipse.dev/glsp/documentation/protocol/

**Comment by planger** [comment]
Thank you very much for the report! I've opened a PR #95 to fix those broken links.
