### ISSUE TITLE
Website certificate expired

### ISSUE THREAD

**Issue by GeorgDaniel** [eclipse-glsp/glsp-website-source#97]
![image](https://github.com/eclipse-glsp/glsp-website-source/assets/56876774/4649ca34-68d9-462f-b28d-19c6194b878a)

Encountered the NET::ERR_CERT_DATE_INVALID error, when trying to visit the website.

**Comment by tortmayr** [comment]
Thanks for reaching out. We are aware of that issue. Our website is hosted on the Eclipse Foundation infrastructure
so we have to wait until the Eclipse IT team resolves the issue (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3828)
In the meantime we have temporary deployed the website on netlify:
https://deploy-preview-98--glsp.netlify.app/

**Comment by tortmayr** [comment]
Should be resolved now
